---
- name: Import RabbitMQ var tasks
  ansible.builtin.include_tasks: vars.yml

- name: Import RabbitMQ install tasks
  ansible.builtin.include_tasks: install.yml

- name: Import RabbitMQ vhost tasks
  ansible.builtin.include_tasks: vhosts.yml

- name: Import RabbitMQ user tasks
  ansible.builtin.include_tasks: users.yml
