---
- name: Converge
  hosts: all
  become: true
  roles:
    - nephelaiio.rabbitmq
  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian'
      changed_when: false
