---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /opt
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        rabbitmq_vhost: molecule_vhost
        rabbitmq_user_name: molecule_user
        rabbitmq_user_pass: molecule_pass
        rabbitmq_user_perm_conf: 'conf'
        rabbitmq_user_perm_write: 'write'
        rabbitmq_user_perm_read: 'read'
verifier:
  name: ansible
