---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos
    image: "geerlingguy/docker-centos7-ansible:latest"
    privileged: True
    command: /usr/lib/systemd/systemd
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    pre_build_image: true
  - name: xenial
    image: "geerlingguy/docker-ubuntu1604-ansible:latest"
    privileged: True
    command: /lib/systemd/systemd
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    pre_build_image: true
  - name: bionic
    image: "geerlingguy/docker-ubuntu1604-ansible:latest"
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    pre_build_image: true
  - name: debian
    image: "geerlingguy/docker-debian9-ansible:latest"
    privileged: True
    command: /lib/systemd/systemd
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    pre_build_image: true
  - name: arch
    image: archlinux/base:latest
    privileged: True
    command: /usr/lib/systemd/systemd
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
