---
name: molecule
on:
  pull_request:
    branches:
      - master
defaults:
  run:
    working-directory: "nephelaiio.rabbitmq"
jobs:
  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - name: default
        image:
          - name: ubuntu2404
            command: /lib/systemd/systemd
          - name: ubuntu2204
            command: /lib/systemd/systemd
          - name: debian13
            command: /lib/systemd/systemd
          - name: debian12
            command: /lib/systemd/systemd
    env:
      MOLECULE_OUTPUT_DIR: /tmp/logs
    steps:
      - name: Run devbox tests
        uses: pokerops/ansible-utils@master
        with:
          run: >
            just
            --set MOLECULE_SCENARIO ${{ matrix.scenario }}
            --set MOLECULE_DOCKER_IMAGE ${{ matrix.image.name }}
            --set MOLECULE_DOCKER_COMMAND ${{ matrix.image.command }}
            requirements test

      - name: Upload install logs
        uses: actions/upload-artifact@v7
        with:
          name: install-${{ matrix.scenario }}-${{ matrix.image.name }}.log
          path: |
            /tmp/logs/*
          if-no-files-found: ignore
        if: always()
